### PR TITLE
fix(error-page) XSS issue when displaying exception message

### PR DESCRIPTION
**Pull request by velcrin**
Closes [BS-15362](https://bonitasoft.atlassian.net/browse/BS-15362)

### CODE REVIEW

**Comment by abirembaut** [comment]
LGTM, but if we do not display the cause of the exception in the 500 error JSP any more (which is a good thing, I think), we should make sure that in all your servlets, for the possible exceptions that haven't been catched already , we catch them and log them before we throw a servlet exception. otherwise we might end up with errors impossible to investigate.
It can be done in another PR, but I am not sure I feel confident merging this PR before this work has been done.

**Comment by velcrin** [comment]
Euh.. yeah I kind of understand also I guess the exception has been logged whenever it was needed. Gonna take forever to go through the code and make sure that every exception is logged when ever it make sense. Also only the message of the exception was displayed which probably didn't actually help that much for the investigation as the stacktrace was lost if it wasn't logged.

**Comment by abirembaut** [comment]
Yep, you are right. And we don't have the stack trace.
But I think tomcat (and other application servers/servlet containers) may already log the servlet exceptions that are not catched. So we may have nothing to do. I will look into it.

**Comment by abirembaut** [comment]
Ucaught exceptions thrown by servlets are logged in catalina.out by default

**Pull request merged**
